### ISSUE TITLE
[Bug]: Problem with loadJSON in jQuery

### ISSUE THREAD

**Issue by johny83br** [tsparticles/tsparticles#2300]
### Contact Details

jonata.marcelino83@gmail.com

### What happened?

Until yesterday the plugin made to jQuery was running, but today in the Chrome crashed.

### Version

2.0.0-beta.0

### Which library are you using?

jQuery (jquery-particles)

### tsParticles Configuration

```json
$("#tsparticles")
  .particles()
  .ajax("particles.json", function (container) {
    // container is the particles container where you can play/pause or stop/start.
    // the container is already started, you don't need to start it manually.
    console.log('callback - particles.js config loaded');
    // let el = document.querySelector(".tsparticles-canvas-el"); 
    // el.setAttribute("height", "300");
  });
```

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell
jQuery.Deferred exception: Cannot read properties of undefined (reading 'loadJSON') TypeError: Cannot read properties of undefined (reading 'loadJSON')
    at HTMLDivElement.<anonymous> (https://cdn.jsdelivr.net/npm/jquery-particles:1:514)
    at Function.each (https://code.jquery.com/jquery-3.2.1.min.js:2:2715)
    at r.fn.init.each (https://code.jquery.com/jquery-3.2.1.min.js:2:1003)
    at Object.ajax (https://cdn.jsdelivr.net/npm/jquery-particles:1:380)
    at HTMLDocument.<anonymous> (https://digietal.com.br/js/funcoes.js?t=1633534862:5:4)
    at j (https://code.jquery.com/jquery-3.2.1.min.js:2:29999)
    at k (https://code.jquery.com/jquery-3.2.1.min.js:2:30313) undefined
r.Deferred.exceptionHook @ jquery-3.2.1.min.js:2


Uncaught TypeError: Cannot read properties of undefined (reading 'loadJSON')
    at HTMLDivElement.<anonymous> (jquery-particles:1)
    at Function.each (jquery-3.2.1.min.js:2)
    at r.fn.init.each (jquery-3.2.1.min.js:2)
    at Object.ajax (jquery-particles:1)
    at HTMLDocument.<anonymous> (funcoes.js?t=1633534862:5)
    at j (jquery-3.2.1.min.js:2)
    at k (jquery-3.2.1.min.js:2)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by johny83br** [comment]
I changed to the version previous, and corrected.

**Comment by matteobruni** [comment]
Yes the current version is still 1.x, I'm working on 2.x but a migration guide will be written since there are a lot of breaking changes as you can see in the 2.x PR here: https://github.com/matteobruni/tsparticles/pull/2297

Anyway if you want to try the new 2.x version you can see the jQuery demo in the `dev` branch here: https://github.com/matteobruni/tsparticles/blob/dev/demo/jquery/views/index.pug

It imports the `.bundle` file of `tsparticles` library to have all previous features bundled together instead of choosing only the needed ones.
