### ISSUE TITLE
Issue with adding a svg file path for polygon mask

### ISSUE THREAD

**Issue by daniel31x13** [tsparticles/tsparticles#2857]
### What do you need?

Hello I'm trying to use a svg file on the website and can't add a relative path to the file, it works with url path but not files on the server.
The regular particles work (so the initialization was done correctly.)
Here's my config file:
```
{
      "background": {
        "color": {
          "value": "#000000"
        },
        "position": "50% 50%",
        "repeat": "no-repeat",
        "size": "cover"
      },
      "fullScreen": {
        "zIndex": 1
      },
      "detectRetina": false,
      "fpsLimit": 30,
      "interactivity": {
        "events": {
          "onClick": {
            "mode": "push"
          },
          "onDiv": {
            "selectors": "#repulse-div",
            "mode": "repulse"
          },
          "onHover": {
            "enable": true,
            "mode": "bubble"
          }
        },
        "modes": {
          "bubble": {
            "distance": 40,
            "duration": 2,
            "opacity": 8,
            "size": 6
          },
          "grab": {
            "distance": 400
          },
          "slow": {
            "factor": 1,
            "radius": 0
          }
        }
      },
      "particles": {
        "color": {
          "value": "#ffffff"
        },
        "links": {
          "color": {
            "value": "#ffffff"
          },
          "distance": 30,
          "enable": true,
          "opacity": 0.4
        },
        "move": {
          "attract": {
            "rotate": {
              "x": 600,
              "y": 1200
            }
          },
          "enable": true,
          "outModes": {
            "default": "bounce",
            "bottom": "bounce",
            "left": "bounce",
            "right": "bounce",
            "top": "bounce"
          },
          "speed": 1
        },
        "number": {
          "density": {
            "area": 2000
          },
          "value": 200
        },
        "opacity": {
          "value": {
            "min": 0.05,
            "max": 0.4
          },
          "animation": {
            "enable": true,
            "minimumValue": 0.05
          }
        },
        "size": {
          "random": {
            "enable": true
          },
          "value": 1,
          "animation": {
            "speed": 40,
            "minimumValue": 0.1
          }
        }
      },
      "polygon": {
        "draw": {
          "enable": true,
          "stroke": {
            "color": {
              "value": "rgba(255,255,255,0.2)"
            },
            "width": 0.5,
            "opacity": 0.2
          }
        },
        "enable": true,
        "inline": {
          "arrangement": "equidistant"
        },
        "move": {
          "radius": 10,
          "type": "path"
        },
        "scale": 0.5,
        "type": "inline",
        "url": "./File.svg"   // the place where I'm having problem with... (the file is on the same location.)
      }
    }
```

And what the console logs:
```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'getElementsByTagName')
    at PolygonMaskInstance.parseSvgPath (PolygonMaskInstance.js:180:1)
    at PolygonMaskInstance.downloadSvgPath (PolygonMaskInstance.js:219:1)
    at async PolygonMaskInstance.initRawData (PolygonMaskInstance.js:366:1)
    at async PolygonMaskInstance.initAsync (PolygonMaskInstance.js:24:1)
    at async Container.init (Container.js:351:1)
    at async Container.start (Container.js:208:1)
    at async Function.loadOptions (Loader.js:71:1)
```

### Version

1.39.0

### Which library are you using?

React.js (react-tsparticles, react-particles-js)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by matteobruni** [comment]
Hi @Daniel31x13,

Can you check your Console Network tab, is there a failed XHR request about that file?

**Comment by daniel31x13** [comment]
Hello @matteobruni,
No there wasn't, looks like it haven't found the file and its giving me the status code of 304 in the .svq file.
Ok so I think my problem is about giving the location of the file because of the `Request URL: http://localhost:3000/Nanoplating.svg
`
when the hierarchy's like this:
![image](https://user-images.githubusercontent.com/93432314/149609182-c117f041-7c76-4d79-804d-5179911e9a03.png)

**Comment by matteobruni** [comment]
`304` is `Not Modified`, it's a cache response, so it's fine.

I was looking on my React demo and I import the `svg` first:

https://github.com/matteobruni/tsparticles/blob/9a7513337a393b3d779df9b95033d7af4712315f/demo/react/src/frames.ts#L4

Then I use that variable in the `url` property:

https://github.com/matteobruni/tsparticles/blob/9a7513337a393b3d779df9b95033d7af4712315f/demo/react/src/frames.ts#L301

Anyway, the SVG file must have at least a `path` tag, without it, it doesn't work.
