### ISSUE TITLE
[Bug]: Error when build with static sites adapter sveltekit

### ISSUE THREAD

**Issue by andreock** [tsparticles/tsparticles#3508]
### Contact Details

andrecanale05@libero.it

### What happened?

Hi, I was trying to build with the Static sites adapter for my site with sveltekit but it gives an error during the build:
[vite-plugin-svelte] C: /Users/Andrea/Desktop/sitename/node_modules/svelte-particles/src/Particles.svelte: 3: 16 Unexpected token
file: C: /Users/Andrea/Desktop/sitename/node_modules/svelte-particles/src/Particles.svelte: 3: 16
 1 | <script lang = "ts">
 2 | import {afterUpdate, createEventDispatcher} from "quick";
 3 | import type {ISourceOptions} from "tsparticles";
                      ^
 4 | import {tsParticles} from "tsparticles";
 5 |
> C: /Users/Andrea/Desktop/sitename/node_modules/svelte-particles/src/Particles.svelte: 3: 16 Unexpected token
   at error (file:///C:/Users/Andrea/Desktop/sitename/node_modules/svelte/compiler.mjs:17691:19)
    at Parser$1.error (file:///C:/Users/Andrea/Desktop/sitename/node_modules/svelte/compiler.mjs:17767:9)
    at Parser$1.acorn_error (file:///C:/Users/Andrea/Desktop/sitename/node_modules/svelte/compiler.mjs:17761:14)
    at Object.read_script [as read] (file:///C:/Users/Andrea/Desktop/sitename/node_modules/svelte/compiler.mjs:8813:16)
    at tag (file:///C:/Users/Andrea/Desktop/sitename/node_modules/svelte/compiler.mjs:16817:33)
    at new Parser$1 (file:///C:/Users/Andrea/Desktop/sitename/node_modules/svelte/compiler.mjs:17726:21)
    at parse$3 (file:///C:/Users/Andrea/Desktop/sitename/node_modules/svelte/compiler.mjs:17858:20)
    at compile (file:///C:/Users/Andrea/Desktop/sitename/node_modules/svelte/compiler.mjs:31871:17)
    at compileSvelte2 (file:///C:/Users/Andrea/Desktop/sitename/node_modules/@sveltejs/vite-plugin-svelte/dist/index.js:319:20)
    at async Object.transform (file:///C:/Users/Andrea/Desktop/sitename/node_modules/@sveltejs/vite-plugin-svelte/dist/index.js:1604:23)
[!] Error: unfinished hook action(s) on exit:
(vite:css) transform "C:/Users/Andrea/Desktop/sitename/src/app.css"
is it a bug or my mistake?

### Version

1.42.1

### Which library are you using?

Svelte (svelte-particles)

### tsParticles Configuration

```json
{
		particles: {
			color: {
				value: '#FFFFFF'
			},
			links: {
				enable: true,
				color: '#FFFFFF'
			},
			move: {
				enable: true
			}
		}
	};
```

### Relevant log output

```shell
[vite-plugin-svelte] C: /Users/Andrea/Desktop/sitename/node_modules/svelte-particles/src/Particles.svelte: 3: 16 Unexpected token
file: C: /Users/Andrea/Desktop/sitename/node_modules/svelte-particles/src/Particles.svelte: 3: 16
 1 | <script lang = "ts">
 2 | import {afterUpdate, createEventDispatcher} from "quick";
 3 | import type {ISourceOptions} from "tsparticles";
                      ^
 4 | import {tsParticles} from "tsparticles";
 5 |
> C: /Users/Andrea/Desktop/sitename/node_modules/svelte-particles/src/Particles.svelte: 3: 16 Unexpected token
   at error (file:///C:/Users/Andrea/Desktop/sitename/node_modules/svelte/compiler.mjs:17691:19)
    at Parser$1.error (file:///C:/Users/Andrea/Desktop/sitename/node_modules/svelte/compiler.mjs:17767:9)
    at Parser$1.acorn_error (file:///C:/Users/Andrea/Desktop/sitename/node_modules/svelte/compiler.mjs:17761:14)
    at Object.read_script [as read] (file:///C:/Users/Andrea/Desktop/sitename/node_modules/svelte/compiler.mjs:8813:16)
    at tag (file:///C:/Users/Andrea/Desktop/sitename/node_modules/svelte/compiler.mjs:16817:33)
    at new Parser$1 (file:///C:/Users/Andrea/Desktop/sitename/node_modules/svelte/compiler.mjs:17726:21)
    at parse$3 (file:///C:/Users/Andrea/Desktop/sitename/node_modules/svelte/compiler.mjs:17858:20)
    at compile (file:///C:/Users/Andrea/Desktop/sitename/node_modules/svelte/compiler.mjs:31871:17)
    at compileSvelte2 (file:///C:/Users/Andrea/Desktop/sitename/node_modules/@sveltejs/vite-plugin-svelte/dist/index.js:319:20)
    at async Object.transform (file:///C:/Users/Andrea/Desktop/sitename/node_modules/@sveltejs/vite-plugin-svelte/dist/index.js:1604:23)
[!] Error: unfinished hook action(s) on exit:
(vite:css) transform "C:/Users/Andrea/Desktop/sitename/src/app.css"
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by matteobruni** [comment]
What TypeScript version are you using @Andrea055?

**Comment by andreock** [comment]
Thanks for answer, Version 4.6.2

**Comment by matteobruni** [comment]
> Thanks for answer, Version 4.6.2

So it's not a TypeScript issue, the `import type` requires TypeScript 3.8 or newer.  Maybe it's an issue with Svelte TypeScript parser or something like that. You can remove it, you can just use the standard `import` if you prefer.

**Comment by andreock** [comment]
I removed import type but now i get this error:
7:32:57 PM [vite] Internal server error: C:/Users/Andrea/Desktop/cracknas/node_modules/svelte-particles/src/Particles.svelte:6:22 Unexpected token
  Plugin: vite-plugin-svelte
  File: C:/Users/Andrea/Desktop/cracknas/node_modules/svelte-particles/src/Particles.svelte
   4 |      import { tsParticles } from "tsparticles";
   5 |
   6 |      export let options: ISourceOptions = {};
                              ^
   7 |      export let url = "";
   8 |      export let id = "tsparticles";

**Comment by andreock** [comment]
I fix with this:
export let options= {};
