### ISSUE TITLE
[Bug]: Failed to resolve entry for package "tsparticles"

### ISSUE THREAD

**Issue by netcore-jroger** [tsparticles/tsparticles#3911]
### Contact Details

sjr_vip@126.com

### Describe the bug

After I use comand `yarn add tsparticles tsparticles-engine react-tsparticles` add these packages, I run `yarn run dev` command. than I got some exceptions.
```log
✘ [ERROR] [plugin vite:dep-scan] Failed to resolve entry for package "tsparticles". The package may have incorrect main/module/exports specified in its package.json: Failed to resolve entry for package "tsparticles". The package may have incorrect main/module/exports specified in its package.json.

    node_modules/vite/dist/node/chunks/dep-27bc1ab8.js:38429:10:
      38429 │     throw new Error(`Failed to resolve entry for package "${id}". ` +
            ╵           ^

  This error came from the "onResolve" callback registered here:

    node_modules/vite/dist/node/chunks/dep-27bc1ab8.js:36968:18:
      36968 │             build.onResolve({
            ╵                   ~~~~~~~~~
```

other issue: https://github.com/vitejs/vite/issues/7754

### Reproduction

https://stackblitz.com/edit/vitejs-vite-iyeunl?file=package.json&terminal=dev

### System Info

```shell
System:
    OS: Windows 10 10.0.22000
    Memory: 9.65 GB / 31.89 GB
  Binaries:
    Node: 14.18.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.18 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.3.0 - ~\AppData\Roaming\npm\npm.CMD
  Browsers:
    Chrome: 100.0.4896.127
    Edge: Spartan (44.22000.120.0), Chromium (100.0.1185.39)
  npmPackages:
    @vitejs/plugin-react-refresh: ^1.3.6 => 1.3.6
    vite: ^2.9.5 => 2.9.5
```

### Used Package Manager

yarn

### Logs

```shell
✘ [ERROR] [plugin vite:dep-scan] Failed to resolve entry for package "tsparticles". The package may have incorrect main/module/exports specified in its package.json: Failed to resolve entry for package "tsparticles". The package may have incorrect main/module/exports specified in its package.json.

    node_modules/vite/dist/node/chunks/dep-27bc1ab8.js:38429:10:
      38429 │     throw new Error(`Failed to resolve entry for package "${id}". ` +
            ╵           ^

    at packageEntryFailure (E:\demo\node_modules\vite\dist\node\chunks\dep-27bc1ab8.js:38429:11)
    at resolvePackageEntry (E:\demo\node_modules\vite\dist\node\chunks\dep-27bc1ab8.js:38425:9)
    at tryNodeResolve (E:\demo\node_modules\vite\dist\node\chunks\dep-27bc1ab8.js:38232:20)
    at Context.resolveId (E:\demo\node_modules\vite\dist\node\chunks\dep-27bc1ab8.js:38040:28)
    at Object.resolveId (E:\demo\node_modules\vite\dist\node\chunks\dep-27bc1ab8.js:36609:55)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async resolve (E:\demo\node_modules\vite\dist\node\chunks\dep-27bc1ab8.js:36821:26)
    at async E:\demo\node_modules\vite\dist\node\chunks\dep-27bc1ab8.js:36978:34
    at async callback (E:\demo\node_modules\esbuild\lib\main.js:921:28)
    at async handleRequest (E:\demo\node_modules\esbuild\lib\main.js:701:30)

  This error came from the "onResolve" callback registered here:

    node_modules/vite/dist/node/chunks/dep-27bc1ab8.js:36968:18:
      36968 │             build.onResolve({
            ╵                   ~~~~~~~~~

    at setup (E:\demo\node_modules\vite\dist\node\chunks\dep-27bc1ab8.js:36968:19)
    at handlePlugins (E:\demo\node_modules\esbuild\lib\main.js:843:23)
    at Object.buildOrServe (E:\demo\node_modules\esbuild\lib\main.js:1137:7)
    at E:\demo\node_modules\esbuild\lib\main.js:2079:17
    at new Promise (<anonymous>)
    at Object.build (E:\demo\node_modules\esbuild\lib\main.js:2078:14)
    at Object.build (E:\demo\node_modules\esbuild\lib\main.js:1927:51)
    at E:\demo\node_modules\vite\dist\node\chunks\dep-27bc1ab8.js:36769:54
    at Array.map (<anonymous>)

  The plugin "vite:dep-scan" was triggered by this import

    src/layout/login/index.tsx:12:25:
      12 │ import { loadFull } from "tsparticles";
         ╵                          ~~~~~~~~~~~~~

Build failed with 1 error:
node_modules/vite/dist/node/chunks/dep-27bc1ab8.js:38429:10: ERROR: [plugin: vite:dep-scan] Failed to resolve entry for package "tsparticles". The package may have incorrect main/module/exports specified in its package.json: Failed to resolve entry for package "tsparticles". The package may have incorrect main/module/exports specified in its package.json.
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitejs/vite/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitejs/vite/blob/main/CONTRIBUTING.md).
- [x] Read the [docs](https://vitejs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitejs/vite/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vite issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitejs/vite/discussions) or join our [Discord Chat Server](https://chat.vitejs.dev/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### Version

2.0.5

### Which library are you using?

React.js (react-tsparticles, react-particles-js)

### tsParticles Configuration

```json
{
  "backgroundMode": {
    "enable": true
  },
  "fpsLimit": 60,
  "particles": {
    "number": {
      "value": 0
    },
    "collisions": {
      "enable": false
    },
    "color": {
      "value": "#ffffff"
    },
    "shape": {
      "type": "circle"
    },
    "opacity": {
      "value": {
        "min": 0.3,
        "max": 0.8
      }
    },
    "size": {
      "value": {
        "min": 1,
        "max": 10
      }
    },
    "move": {
      "enable": true,
      "size": true,
      "speed": 5,
      "direction": "none",
      "outModes": {
        "default": "destroy"
      },
      "trail": {
        "enable": true,
        "fillColor": "#000000",
        "length": 3
      }
    }
  },
  "detectRetina": true,
  "background": {
    "color": "#000"
  },
  "emitters": {
    "direction": "none",
    "rate": {
      "delay": 0.25,
      "quantity": 10
    },
    "position": {
      "x": 50,
      "y": 50
    },
    "size": {
      "width": 0,
      "height": 0
    },
    "spawnColor": {
      "value": "#ff0000",
      "animation": {
        "h": {
          "enable": true,
          "speed": 5
        },
        "l": {
          "enable": true,
          "speed": 0,
          "offset": {
            "min": 20,
            "max": 80
          }
        }
      }
    }
  }
}
```

### What browsers are you seeing the problem on?

Firefox

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by n8sabes** [comment]
@netcore-jroger Check out issue #3910. Following steps in the Migration Articles, I was able to get `1.x` code functional with little effort. I believe a proper `2.x` migration may take a little more thought to capture all the benefits offered.

1. Install the packages as defined in the migration articles
2. Replace all "tsparticles" imports to "tsparticles-engine"
3. Add import { loadFull } from "tsparticles"; in the imports, or its RequireJS version. This requires the new 2.0.x version, you can install it using npm install tsparticles@next
4. Call loadFull
a) If using a React/Vue/Angular/Svelte or other kind of component: in particlesInit/init property, passing the same parameter coming from the init function to loadFull
b) If not just call loadFull(tsParticles) before any tsParticles usage

**Comment by matteobruni** [comment]
Thanks @netcore-jroger, I've found the problem, there's a `"module": "esm/index.js"` that points to a non existing file, this will be fixed soon!

I need to check all build scripts (around 80 packages 😅) to see if there are similar cases
