### ISSUE TITLE
[Bug]: RangeError: Maximum call stack size exceeded.

### ISSUE THREAD

**Issue by YQisme** [tsparticles/tsparticles#4831]
### Contact Details

eanyang7@gmail.com

### What happened?

A bug happened!
In dev mode, I successfully added particle effects to the blog using vitepress, but an error occurred during building.
RangeError: Maximum call stack size exceeded.

### tsParticles Version

"vue3-particles": "^2.5.3"

### Which library are you using?

Vue.js 3.x (vue3-particles, particles.vue3)

### tsParticles Configuration

```json
<template>
    <Particles id="tsparticles" :options="options" :particlesInit="particlesInit" />
</template>
<script lang="ts">
import Particles from "vue3-particles";

import type { Engine } from "tsparticles-engine";
import { loadSlim } from "tsparticles-slim"
export default {
    data() {
        return {
            options: {
                fullScreen: {
                    enable: true, 
                    zIndex: -1,  
                },
                interactivity: {
                    events: {
                        onclick: {
                            enable: true,
                            mode: "push",
                        },
                        onHover: {
                            enable: true,
                            mode: "repulse",  
                        },
                    },
                    modes: {
                        push: {
                            quantity: 10  
                        },
                        repulse: {
                            distance: 100,
                        },
                    },
                },

                particles: {

                    links: {
                        distance: 100, 
                        enable: true,
                        color: "#000", 
                    },
                    move: {
                        enable: true,
                        speed: { min: 1, max: 5 },
                    },
                    opacity: {
                        value: { min: 0.3, max: 0.7 }
                    },
                    size: {
                        value: { min: 1, max: 3 }
                    },
                },
            },
        };
    },
    methods: {
        async particlesInit(engine: Engine) {
            await loadSlim(engine);
        }
    },
};

</script>
```

### What browsers are you seeing the problem on?

Microsoft Edge

### Relevant log output

```shell
pnpm build

> test@1.0.0 build E:\Github_Projects\MYDLVUG.github.io 
> vitepress build docs

vitepress v1.0.0-alpha.29
✓ building client + server bundles...
Trace
    at file:///E:/Github_Projects/MYDLVUG.github.io/docs/.vitepress/.temp/app.js:21:9
    at ModuleJob.run (node:internal/modules/esm/module_job:185:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:281:24)
    at async build (file:///E:/Github_Projects/MYDLVUG.github.io/node_modules/vitepress/dist/node/serve-fcdc8868.js:42002:24)
✖ rendering pages...
build error:
 RangeError: Maximum call stack size exceeded
    at Object.hasOwnProperty (<anonymous>)
    at Object.hasOwn (E:\Github_Projects\MYDLVUG.github.io\node_modules\@vue\shared\dist\shared.cjs.prod.js:493:45)
    at Object.set (E:\Github_Projects\MYDLVUG.github.io\node_modules\@vue\runtime-core\dist\runtime-core.cjs.prod.js:2516:25)
    at Object.defineProperty (E:\Github_Projects\MYDLVUG.github.io\node_modules\@vue\runtime-core\dist\runtime-core.cjs.prod.js:2545:18)
    at Function.defineProperty (<anonymous>)
    at Object.def (E:\Github_Projects\MYDLVUG.github.io\node_modules\@vue\shared\dist\shared.cjs.prod.js:558:12)    at Object.markRaw (E:\Github_Projects\MYDLVUG.github.io\node_modules\@vue\reactivity\dist\reactivity.cjs.prod.js:918:12)
    at setupStatefulComponent (E:\Github_Projects\MYDLVUG.github.io\node_modules\@vue\runtime-core\dist\runtime-core.cjs.prod.js:5754:33)
    at setupComponent (E:\Github_Projects\MYDLVUG.github.io\node_modules\@vue\runtime-core\dist\runtime-core.cjs.prod.js:5743:11)
    at renderComponentVNode (E:\Github_Projects\MYDLVUG.github.io\node_modules\@vue\server-renderer\dist\server-renderer.cjs.prod.js:169:17)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by YQisme** [comment]
The error statement is

`const hasOwn = (val, key) => hasOwnProperty.call(val, key);`

**Comment by matteobruni** [comment]
> The error statement is
> 
> `const hasOwn = (val, key) => hasOwnProperty.call(val, key);`

And it’s not part of the `tsparticles` repository. Please share a sample project so I can see the code to replicate the issue

**Comment by YQisme** [comment]
> 

I created a [demo project repository](https://github.com/YQisme/tsparticles_test) for this bug,you can clone it and debug it. Thanks a lot!
https://github.com/YQisme/tsparticles_test.git

**Comment by matteobruni** [comment]
> I created a [demo project repository](https://github.com/YQisme/tsparticles_test) for this bug,you can clone it and debug it. Thanks a lot!
> https://github.com/YQisme/tsparticles_test.git

Wrap `<CustomParticles />` in a `<ClientOnly>` tag, tsParticles cannot run server side

**Comment by YQisme** [comment]
> > I created a [demo project repository](https://github.com/YQisme/tsparticles_test) for this bug,you can clone it and debug it. Thanks a lot!
> > https://github.com/YQisme/tsparticles_test.git
> 
> Wrap `<CustomParticles />` in a `<ClientOnly>` tag, tsParticles cannot run server side

Great! It worked. Thank you again!
