### ISSUE TITLE
tsparticles/astro component setup

### ISSUE THREAD

**Issue by greneit** [tsparticles/tsparticles#4915]
### Contact Details

robin@greneit.com

### What happened?

I am using the Astro framework to build my website. However, I am new to this. I want the particles effect so I started to install the tsparticles/astro component (https://github.com/tsparticles/astro) Following the instruction, I put in the following code into astro.config.mjs:
```

import Particles from "astro-particles";

import type { ISourceOptions } from "tsparticles-engine";

const options: ISourceOptions = {
    background: {
        color: "#000"
    },
    fullScreen: {
        zIndex: -1
    },
    particles: {
        move: {
            enable: true
        }
    }
};
```

My package.json looks like this:
```

{
  "name": "astrolus",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "dev": "astro dev",
    "start": "astro dev",
    "build": "astro build",
    "preview": "astro preview",
    "astro": "astro"
  },
  "dependencies": {
    "astro": "^2.0.16",
    "astro-particles": "^2.9.3",
    "tsparticles": "^2.9.3"
  },
  "devDependencies": {
    "@astrojs/tailwind": "^3.0.1"
  }
}

And this is the error I get when I run the dev environment:

`robinedwards@pop-os:/media/robinedwards/data/Documents/Development/greneit/greneit-astro/website$ sudo npm run dev

> astrolus@0.0.1 dev
> astro dev

14:36:28 [astro] Unable to load /media/robinedwards/data/Documents/Development/greneit/greneit-astro/website/astro.config.mjs

 error   Parse failure: Unexpected token (7:12)
  At file: /media/robinedwards/data/Documents/Development/greneit/greneit-astro/website/astro.config.mjs
  Contents of line 7: import type { ISourceOptions } from "tsparticles-engine";
  File:
    /media/robinedwards/data/Documents/Development/greneit/greneit-astro/website/node_modules/vite/dist/node/chunks/dep-ca21228b.js:51834:15
  Code:
    51833 |         const line = err.loc.line;
    > 51834 |         throw new Error(`Parse failure: ${err.message}\nAt file: ${url}\nContents of line ${line}: ${code.split('\n')[line - 1]}`);
            |               ^
      51835 |     }
      51836 |     let uid = 0;
      51837 |     const deps = new Set();
  Stacktrace:
Error: Parse failure: Unexpected token (7:12)
At file: /media/robinedwards/data/Documents/Development/greneit/greneit-astro/website/astro.config.mjs
Contents of line 7: import type { ISourceOptions } from "tsparticles-engine";
    at ssrTransformScript (file:///media/robinedwards/data/Documents/Development/greneit/greneit-astro/website/node_modules/vite/dist/node/chunks/dep-ca21228b.js:51834:15)
    at ssrTransform (file:///media/robinedwards/data/Documents/Development/greneit/greneit-astro/website/node_modules/vite/dist/node/chunks/dep-ca21228b.js:51809:12)
    at Object.ssrTransform (file:///media/robinedwards/data/Documents/Development/greneit/greneit-astro/website/node_modules/vite/dist/node/chunks/dep-ca21228b.js:61184:20)
    at loadAndTransform (file:///media/robinedwards/data/Documents/Development/greneit/greneit-astro/website/node_modules/vite/dist/node/chunks/dep-ca21228b.js:39502:24)

`


```
Can you please let me know what is happening.

### tsParticles Version

2.9.3

### Which library are you using?

Vanilla (tsparticles)

### tsParticles Configuration

```json
background: {
        color: "#000"
    },
    fullScreen: {
        zIndex: -1
    },
    particles: {
        move: {
            enable: true
        }
    }
```

### What browsers are you seeing the problem on?

Firefox

### Relevant log output

```shell
14:36:28 [astro] Unable to load /media/robinedwards/data/Documents/Development/greneit/greneit-astro/website/astro.config.mjs

 error   Parse failure: Unexpected token (7:12)
  At file: /media/robinedwards/data/Documents/Development/greneit/greneit-astro/website/astro.config.mjs
  Contents of line 7: import type { ISourceOptions } from "tsparticles-engine";
  File:
    /media/robinedwards/data/Documents/Development/greneit/greneit-astro/website/node_modules/vite/dist/node/chunks/dep-ca21228b.js:51834:15
  Code:
    51833 |         const line = err.loc.line;
    > 51834 |         throw new Error(`Parse failure: ${err.message}\nAt file: ${url}\nContents of line ${line}: ${code.split('\n')[line - 1]}`);
            |               ^
      51835 |     }
      51836 |     let uid = 0;
      51837 |     const deps = new Set();
  Stacktrace:
Error: Parse failure: Unexpected token (7:12)
At file: /media/robinedwards/data/Documents/Development/greneit/greneit-astro/website/astro.config.mjs
Contents of line 7: import type { ISourceOptions } from "tsparticles-engine";
    at ssrTransformScript (file:///media/robinedwards/data/Documents/Development/greneit/greneit-astro/website/node_modules/vite/dist/node/chunks/dep-ca21228b.js:51834:15)
    at ssrTransform (file:///media/robinedwards/data/Documents/Development/greneit/greneit-astro/website/node_modules/vite/dist/node/chunks/dep-ca21228b.js:51809:12)
    at Object.ssrTransform (file:///media/robinedwards/data/Documents/Development/greneit/greneit-astro/website/node_modules/vite/dist/node/chunks/dep-ca21228b.js:61184:20)
    at loadAndTransform (file:///media/robinedwards/data/Documents/Development/greneit/greneit-astro/website/node_modules/vite/dist/node/chunks/dep-ca21228b.js:39502:24)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by matteobruni** [comment]
Hi @greneit, it looks it's something related to your TypeScript configuration, you can remove the whole `import type` line and `: ISourceOptions` from the `options` declaration. It **should** work with JavaScript then since all the TypeScript code now is in the component but I hope it's going to be built using the config inside that.

I'm going to close this here, if you still needs help please open an issue in the component repository. I'd like to keep things more organized now. It's easier to find issues about the Astro component in the Astro dedicated repository.

**Comment by greneit** [comment]
Hi Matteo
Thank for looking into this and for your suggestion. I will remove the import from the config.
Have a great day.
Best Wishes
Robin
Get BlueMail <https://bluemail.me> for Desktop
Matteo Bruni wrote:
Hi @greneit <https://github.com/greneit> , it looks it's something related to your TypeScript configuration, you can remove the whole import type line and : ISourceOptions from the options declaration. It should work with JavaScript then since all the TypeScript code now is in the component but I hope it's going to be built using the config inside that.
I'm going to close this here, if you still needs help please open an issue in the component repository. I'd like to keep things more organized now. It's easier to find issues about the Astro component in the Astro dedicated repository.
